sonar.projectKey=RidECI-Legacy_galaga-travel-service2
sonar.organization=rideci-legacy-1
sonar.projectName=galaga-travel-service

sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.tests=test/unit

sonar.test.inclusions=**/*.spec.ts

sonar.exclusions=**/*.module.ts,src/main.ts,src/types/**,dist/**,node_modules/**

sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

sonar.sourceEncoding=UTF-8
